apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: YOUR_DOCKERHUB_NAME/api-image:v1.0
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: myns
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 3000
      targetPort: 8080
